// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkSt.Data.Models;

public partial class Bill
{
    public int BillId { get; set; }

    public int? BillDetailId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly Date { get; set; }

    public double SubTotal { get; set; }

    public int? VoucherId { get; set; }

    public double DiscountAmount { get; set; }

    public double TotalAmount { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public virtual BillDetail BillDetail { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Voucher Voucher { get; set; }
}