// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkSt.Data.Models;

public partial class BillDetail
{
    public int BillDetailId { get; set; }

    public int MilkId { get; set; }

    public int Quantity { get; set; }

    public double Price { get; set; }

    public double Amount { get; set; }

    public double Discount { get; set; }

    public double Tax { get; set; }

    public double Total { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    public virtual Milk Milk { get; set; }
}