// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkSt.Data.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string FacebookId { get; set; }

    public string Language { get; set; }

    public string CustType { get; set; }

    public string Note { get; set; }

    public string TotalSale { get; set; }

    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();
}