// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkSt.Data.Models;

public partial class Milk
{
    public int MilkId { get; set; }

    public string Name { get; set; }

    public string Brand { get; set; }

    public string ManufactureIn { get; set; }

    public double Weight { get; set; }

    public string MilkType { get; set; }

    public DateOnly Expiry { get; set; }

    public string Description { get; set; }

    public double Price { get; set; }

    public double Discount { get; set; }

    public virtual ICollection<BillDetail> BillDetails { get; set; } = new List<BillDetail>();
}