// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkSt.Data.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Name { get; set; }

    public double Discount { get; set; }

    public DateOnly Expiry { get; set; }

    public int Quantity { get; set; }

    public string Description { get; set; }

    public DateOnly CreatedDate { get; set; }

    public DateOnly? UpdatedDate { get; set; }

    public int RedemptionCount { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();
}